version: "3.8"

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - PDF_SERVICE_URL=http://pdf-service:8000/convert
      - AGENT_SERVICE_URL=http://agent-service:8964/transcribe
      - TTS_SERVICE_URL=http://tts-service:8888/generate_tts
    depends_on:
      - pdf-service
      - agent-service
      - tts-service
    networks:
      - app-network

  agent-service:
    build:
      context: ./AgentService
      dockerfile: Dockerfile
    ports:
      - "8964:8964"
    networks:
      - app-network

  pdf-service:
    build:
      context: ./PDFService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network

  tts-service:
    build:
      context: ./TTSService
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge