version: "3.8"

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8002:8002"
    environment:
      - PDF_SERVICE_URL=http://pdf-service:8003
      - AGENT_SERVICE_URL=http://agent-service:8964
      - TTS_SERVICE_URL=http://tts-service:8888
    depends_on:
      - pdf-service
      - agent-service
      - tts-service
    networks:
      - app-network

  agent-service:
    build:
      context: ./AgentService
      dockerfile: Dockerfile
    ports:
      - "8964:8964"
    environment:
      - NIM_KEY=${NIM_KEY}
    networks:
      - app-network

  pdf-service:
    build:
      context: ./PDFService
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - app-network

  tts-service:
    build:
      context: ./TTSService
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge