services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly no
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: minio server /minio_data --console-address ":9001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 5

  api-service:
    image: nvcr.io/pfteb4cqjzrs/playground/api-service:1.1
    ports:
      - "8002:8002"
    environment:
      - PDF_SERVICE_URL=http://pdf-service:8003
      - AGENT_SERVICE_URL=http://agent-service:8964
      - TTS_SERVICE_URL=http://tts-service:8889
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - pdf-service
      - agent-service
      - tts-service
    networks:
      - app-network

  agent-service:
    image: nvcr.io/pfteb4cqjzrs/playground/agent-service:1.1
    ports:
      - "8964:8964"
    environment:
      - NIM_KEY=${NIM_KEY}
      - REDIS_URL=redis://redis:6379
      - MODEL_CONFIG_PATH=/app/config/models.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./models.json:/app/config/models.json
    depends_on:
      - redis
    networks:
      - app-network

  pdf-service:
    image: nvcr.io/pfteb4cqjzrs/playground/pdf-service:1.1
    ports:
      - "8003:8003"
    environment:
      - REDIS_URL=redis://redis:6379
      - MODEL_API_URL=${MODEL_API_URL:-https://pdf-gyrdps568.brevlab.com}
    depends_on:
      - redis
    networks:
      - app-network

  tts-service:
    image: nvcr.io/pfteb4cqjzrs/playground/tts-service:1.1
    ports:
      - "8889:8889"
    environment:
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge