apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: agent-service
  name: agent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: agent-service
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: agent-service
    spec:
      containers:
        - image: agent-service
          name: agent-service
          ports:
            - containerPort: 8964
              protocol: TCP
      restartPolicy: Always
