apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api-service
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-service
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: api-service
    spec:
      containers:
        - env:
            - name: AGENT_SERVICE_URL
              value: http://agent-service:8964/transcribe
            - name: PDF_SERVICE_URL
              value: http://pdf-service:8000/convert
            - name: TTS_SERVICE_URL
              value: http://tts-service:8888/generate_tts
          image: api-service
          name: api-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
