apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: pdf-service
  name: pdf-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pdf-service
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: pdf-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.ngcImagePullSecretName }}
      containers:
        - image: nvcr.io/pfteb4cqjzrs/playground/pdf-service:0.2
          name: pdf-service
          ports:
            - containerPort: 8003
              protocol: TCP
      restartPolicy: Always
