apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: tts-service
  name: tts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tts-service
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: tts-service
    spec:
      containers:
        - env:
            - name: ELEVENLABS_API_KEY
              value: sk_aa6637a992e54749f52dd2cd3ef761acddb77093e378c242
          image: tts-service
          name: tts-service
          ports:
            - containerPort: 8888
              protocol: TCP
      restartPolicy: Always
