# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Podcast Prompts"

prompts:
  - file://./prompts_iter.py:PodcastPrompts.raw_outline_prompt

providers:
  - id: "https://integrate.api.nvidia.com/v1/chat/completions"
    config:
      method: "POST"
      headers:
        "Content-Type": "application/json"
        "Authorization": "Bearer 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"
      body:
        model: "meta/llama-3.1-405b-instruct"
        messages:
          - role: "user"
            content: "{{prompt}}"
      responseParser: "json.choices[0].message.content"

tests:
  - vars:
      duration: 10
      text: file://./eval.txt
