name: Build and Push Services

on:
  push:
    tags:
      - "v*.*"

jobs:
  # Common setup job to get version
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

  api-service:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_TOKEN }}
      - name: Build and push api-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/APIService/Dockerfile
          push: true
          tags: nvcr.io/pfteb4cqjzrs/playground/api-service:${{ needs.setup.outputs.version }}

  agent-service:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_TOKEN }}
      - name: Build and push agent-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/AgentService/Dockerfile
          push: true
          tags: nvcr.io/pfteb4cqjzrs/playground/agent-service:${{ needs.setup.outputs.version }}

  pdf-service:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_TOKEN }}
      - name: Build and push pdf-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/PDFService/Dockerfile
          push: true
          tags: nvcr.io/pfteb4cqjzrs/playground/pdf-service:${{ needs.setup.outputs.version }}

  pdf-model-api:
    needs: setup
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_TOKEN }}
      - name: Build and push pdf-service
        uses: docker/build-push-action@v6
        with:
          context: services/PDFService/PDFModelService
          file: services/PDFService/PDFModelService/Dockerfile.api
          push: true
          tags: nvcr.io/pfteb4cqjzrs/playground/pdf-model-api:${{ needs.setup.outputs.version }}

  pdf-model-worker:
    needs: setup
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_TOKEN }}
      - name: Build and push pdf-service
        uses: docker/build-push-action@v6
        with:
          context: services/PDFService/PDFModelService
          file: services/PDFService/PDFModelService/Dockerfile.worker
          push: true
          tags: nvcr.io/pfteb4cqjzrs/playground/pdf-model-worker:${{ needs.setup.outputs.version }}

  tts-service:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_TOKEN }}
      - name: Build and push tts-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/TTSService/Dockerfile
          push: true
          tags: nvcr.io/pfteb4cqjzrs/playground/tts-service:${{ needs.setup.outputs.version }}
