name: PR Test Suite

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}" > .env
          echo "NIM_KEY=${{ secrets.NIM_KEY }}" >> .env
          echo "MAX_CONCURRENT_REQUESTS=10" >> .env

      - name: Start services in detached mode
        run: make ci DETACH=1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements-test.txt  # Make sure this file exists with your test dependencies

      - name: Run monologue E2E tests
        run: python tests/test.py --monologue --target bofa-context.pdf --context citi-context.pdf

      - name: Run podcast E2E tests
        run: python tests/test.py --target bofa-context.pdf --context citi-context.pdf
