services:
  pdf-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8003:8003"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TEMP_FILE_DIR=/tmp/pdf_conversions
    volumes:
      - pdf_temp:/tmp/pdf_conversions
    depends_on:
      - redis
      - celery-worker
    restart: unless-stopped

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TEMP_FILE_DIR=/tmp/pdf_conversions
    volumes:
      - pdf_temp:/tmp/pdf_conversions
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis_data:
  pdf_temp: